<section class="row mt-5">    

    <div class="col-md-5 offset-md-3">
    
        <div class="card card-body">
        <h1 class="col text-center">Entre com sua conta</h1>

        <!-- Para acessar como administrador use: EMAIL: admin@admin.com  SENHA: 123456   -->
        <h6 class="col text-center">ou como administrador </h6>
            <form action="" method="post">
                <input name="email" type="email" placeholder="Email" class="form-control form-control-lg mb-3">

                <input name="password" type="password" placeholder="Senha" class="form-control form-control-lg mb-3">

                <div class="d-grid">
                    <button class="btn btn-dark btn-lg">Entrar</button>
                </div>
            </form>
        </div>
    </div>
</section>