<nav class="mt-3 d-flex justify-content-between">
    <div class="text-start">
        <a href="/login" class="btn btn-outline-dark">Inicio</a>
        
        <a href="/alunos/listar" class="btn btn-outline-dark">Alunos</a>
        
        <a href="/professores/listar" class="btn btn-outline-dark">Professor</a>
        
        <a href="/cursos/listar" class="btn btn-outline-dark">Cursos</a> 
        
        <a href="/categorias/listar" class="btn btn-outline-dark">Categorias</a>
        
        <a href="/usuarios/listar" class="btn btn-outline-dark">Usuarios</a> 
    </div>
    <div class="d-flex">
        <p class=" me-2 pt-2">Bem Vindo(a) <?php echo App\Security\UserSecurity::getUser()->name ?></p>
        <div class="  ms-2 pt-1 text-end">
            <a href="/desconectar" class="btn btn-outline-danger">Desconectar</a>
        </div>
    </div>
</nav>

<hr>

<section class="row mt-5">
    <div class="col-md-4 offset-md-4">
    
        <div class="card card-body">
        <h1 class="col-md-4 offset-md-4">Login</h1>
            <form action="" method="post">
                <input name="email" type="email" placeholder="Email" class="form-control form-control-lg mb-3">

                <input name="password" type="password" placeholder="Senha" class="form-control form-control-lg mb-3">

                <div class="d-grid">
                    <button class="btn btn-dark btn-lg">Entrar</button>
                </div>
            </form>
        </div>
    </div>
</section>